### ISSUE TITLE
Dashboard 2.0 Support

### ISSUE THREAD

**Issue by 1-tempest** [bartbutenaers/node-red-contrib-ui-web-push#10]
Is there a chance this might get rewritten to support dashboard 2.0?

**Comment by bartbutenaers** [comment]
Hi @13th-tempest,
Sorry for the delay.  Seems I get not notifications about issues for this node.
I hope to be able to finish a beta implementation of this node for dashboard 2.0 this week.
Will announce it on the Discourse forum as soon as ready.
Bart
